### PR TITLE
Lad2 added

### PR DESCRIPTION
**Pull request by maksimkha**

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
You have a problem labelling input fields. You shouldn't use `h3` or `p` for that. Use `label` instead.

**Comment by maksimkha** [comment]
swaped p's and h's is forms for labels, you can check using the same links

**Comment by gmltA** [comment]
Why don't I see code changes here then?

**Comment by maksimkha** [comment]
so i should add commit, right? oh there is problem with links? anyway just in case, i also add tagging for mobile version, hope now everything is ok

**Review by gmltA — COMMENTED** [review]
That's a <kbd>7</kbd> now. Is that enough?

**Review by gmltA — APPROVED** [review]

**Pull request merged**
